version: "3"

services:
  mysql:
    image: mysql:5.7.36
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    depends_on:
      - mysql
    ports:
      - 8081:8080

  php:
    build: docker/php
    restart: always
    working_dir: /usr/src/php
    entrypoint: php
    command: -S 0.0.0.0:8080 -t public
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/php
    depends_on:
      - mysql
